#!/bin/bash

if [ $# == 0 ]; then
        echo "Uso: ./cpjar <master-name>";
        exit;
fi;

MASTER=$1;

echo "Building hadoop app..."
#mvn clean package assembly:single -Dmaven.test.skip=true
mvn clean install

echo "Copying jar files to $MASTER..."
scp -r target/spark-imrApriori-1.0.jar hdp@$MASTER:/home/hdp/app-jar/

echo "done "; date;

